[package]
name = "xkcd"
version = "0.1.0-alpha.0"
edition = "2021"
rust-version = "1.56.1"
publish = false

[dependencies]
reqwest = { version = "0.11.9", features = ["json", "gzip", "brotli", "deflate"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1", features = ["full"] }
